---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - php7.4
        - docker
      state: latest
      update_cache: yes
