- name: Install Apache2
  tags: apache2,php
  package:
    name:
      - apache2
      - php7.4
      - libapache2-mod-php7.4
      - php-curl
      - php-gd
      - php-json
      - php-mbstring
      - php-xml
    state: latest
  register: apache


- name: copy basic phpinfo to server
  tags: apache2,php
  copy:
    src: default_php
    dest: /var/www/html/phpinfo.php
    owner: root
    group: root
    mode: 0644
  register: apache

- name: copy basic html to server
  tags: apache2,html
  copy:
    src: default_html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  register: apache

- name: copy basic html to server
  tags: apache2,html
  copy:
    src: facts
    dest: /var/www/html/metrics.php
    owner: root
    group: root
    mode: 0644
  register: apache

- name: copy current facts to server
  tags: apache2,html
  copy:
    src: facts
    dest: /var/www/html/js/facts.json
    owner: root
    group: root
    mode: 0644
  register: apache

- name: Ensure Apache2 is running
  tags: apache,service
  service:
    name: apache2
    state: started

- name: update apache changes
  tags: apache,webmmaster
  service:
    name: apache2
    state: restarted
  when:  apache.changed
