---

- hosts: all
  become: true
  tasks:

  - name: Uninstall Apache
    apt:
      name: apache2
      state: absent
      purge: yes
      autoremove: true
      autoclean: true

  - name: Delete content & directory
    file:
      state: absent
      path: /etc/apache2/


