---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Repos
    package:
      update_cache: yes

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
      state: absent
      purge: yes

#  - name: install TF
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      mode: 0755
#      owner: root
#      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2
    tags: apache2,php
    package:
      name:
        - apache2
        - php7.4
        - libapache2-mod-php
      state: absent
      purge: yes

#  - name: copy basic phpinfo to server
#    tags: apache2,php
#    copy:
#      src: default_php
#      dest: /var/www/html/index.php
#      owner: root
#      group: root
#      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB and PHPMyAdmin
    tags: db,mariadb,phpmyadmin
    package:
      name:
        - mariadb-server
        - php7.4
        - phpmyadmin
        - php-mbstring
        - php-zip
        - php-gd
        - php-json
        - php-curl
      state: absent
      purge: yes

- hosts: file_servers
  become: true
  tasks:

  - name: Install GlusterFS
    tags: file,gluster
    package:
      name:
        - glusterfs-server
      state: absent
      purge: yes
