---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Repos
    package:
      update_cache: yes

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install TF
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: create dev user
    tags: always
    user:
      name: dev
      groups: root

  - name: add ssh key for dev
    tags: always
    authorized_key:
      user: dev
      key: "your-ssh-key"

  - name: add sudoers file for dev
    tags: always
    copy:
      src: sudoer_dev
      dest: /etc/sudoers.d/dev
      owner: root
      group: root
      mode: 0440

- hosts: db_servers
  become: true
  tasks:

  - name: create dev user
    tags: always
    user:
      name: dev
      groups: root

  - name: add ssh key for dev
    tags: always
    authorized_key:
      user: dev
      key: "your-ssh-key"

  - name: add sudoers file for dev
    tags: always
    copy:
      src: sudoer_dev
      dest: /etc/sudoers.d/dev
      owner: root
      group: root
      mode: 0440

- hosts: file_servers
  become: true
  tasks:

  - name: create dev user
    tags: always
    user:
      name: dev
      groups: root

  - name: add ssh key for dev
    tags: always
    authorized_key:
      user: dev
      key: "your-ssh-key"

  - name: add sudoers file for dev
    tags: always
    copy:
      src: sudoer_dev
      dest: /etc/sudoers.d/dev
      owner: root
      group: root
      mode: 0440

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2
    tags: apache2,php
    package:
      name:
        - apache2
        - php7.4
        - libapache2-mod-php7.4
        - php-curl
        - php-gd
        - php-json
        - php-mbstring
        - php-xml
      state: latest
    register: apache

  - name: copy basic phpinfo to server
    tags: apache2,php
    copy:
      src: default_php
      dest: /var/www/html/phpinfo.php
      owner: root
      group: root
      mode: 0644
    register: apache

  - name: copy basic html to server
    tags: apache2,html
    copy:
     src: default_html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644
    register: apache

  - name: copy basic html to server
    tags: apache2,html
    copy:
     src: facts
     dest: /var/www/html/metrics.php
     owner: root
     group: root
     mode: 0644
    register: apache

  - name: copy current facts to server
    tags: apache2,html
    copy:
     src: facts
     dest: /var/www/html/js/facts.json
     owner: root
     group: root
     mode: 0644
    register: apache

  - name: Ensure Apache2 is running
    tags: apache,service
    service:
      name: apache2
      state: started

  - name: update apache changes
    tags: apache,webmmaster
    service:
      name: apache2
      state: restarted
    when:  apache.changed

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB and PHPMyAdmin
    tags: db,mariadb,phpmyadmin
    package:
      name:
        - mariadb-server
        - php7.4
        - phpmyadmin
        - php-mbstring
        - php-zip
        - php-gd
        - php-json
        - php-curl
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: Install GlusterFS
    tags: file,gluster
    package:
      name:
        - glusterfs-server
      state: latest
